"""empty message

Revision ID: 026a4bebef0b
Revises: e8f27d6b7e43
Create Date: 2020-11-30 21:42:43.849783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '026a4bebef0b'
down_revision = 'e8f27d6b7e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('expenses', 'item',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('expenses', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'item',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('expenses', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
