"""empty message

Revision ID: 0ef8f335e4bd
Revises: 
Create Date: 2020-11-29 20:09:18.816919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8f335e4bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('idexpenses', sa.INTEGER(), nullable=False),
    sa.Column('item', sa.VARCHAR(length=45), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(timezone=10), nullable=True),
    sa.PrimaryKeyConstraint('idexpenses')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
