"""empty message

Revision ID: 0f9ead3346e1
Revises: 0ef8f335e4bd
Create Date: 2020-11-30 20:46:03.728940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9ead3346e1'
down_revision = '0ef8f335e4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
