"""empty message

Revision ID: 70c13cd9263e
Revises: 0f9ead3346e1
Create Date: 2020-11-30 20:48:04.067923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c13cd9263e'
down_revision = '0f9ead3346e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
