"""empty message

Revision ID: e8f27d6b7e43
Revises: 70c13cd9263e
Create Date: 2020-11-30 20:48:47.112045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f27d6b7e43'
down_revision = '70c13cd9263e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
